### ISSUE TITLE
Http dumps not working

### ISSUE THREAD

**Issue by gander** [buggregator/server#108]
What more can I say? Whatever I send, I get a 404 and no result in the panel. How do I provide more details?

```http
GET http://http-dump@localhost:8000/user/3/update
```
```http
HTTP/1.1 404 Not Found
Server: nginx/1.20.2
Date: Sun, 03 Dec 2023 20:58:54 GMT
Content-Length: 0
Connection: keep-alive
Vary: Origin
```

```
<Response body is empty>

Response code: 404 (Not Found); Time: 2ms (2 ms); Content length: 0 bytes (0 B)
```

```yaml
services:
    buggregator:
        image: ghcr.io/buggregator/server:latest
        pull_policy: always
        restart: always
        ports:
            - 127.0.0.1:8000:8000
```
