### ISSUE TITLE
Add Helm Chart for kubernetes

### ISSUE THREAD

**Issue by butschster** [buggregator/server#140]
**Hello everyone,**

We are looking to enhance the deployment process of the **Buggregator Server** in Kubernetes environments, aiming to make it more streamlined and accessible. To achieve this, we want to develop a Helm chart that encapsulates all the necessary configurations and simplifies the setup process.

**Project Goals:**

- **Ease of Use:** Simplify the deployment of Buggregator Server on Kubernetes.
- **Configuration Flexibility:** Allow users to easily customize the deployment according to their needs through Helm values.
- **Scalability and Reliability:** Ensure the Helm chart supports scalable deployments and integrates well with Kubernetes' native features for high availability.

**We Need Your Help!** We are reaching out to the community for help with creating this Helm chart. Whether you're experienced with Helm or Kubernetes, or are looking to get involved in open source development, we welcome your contributions!

**How You Can Help:**

- **Chart Development:** Contributing to the initial creation of the Helm chart, including templates for deployments, services, and other necessary Kubernetes resources.
- **Documentation:** Assisting in writing clear, user-friendly documentation for setting up the Helm chart.
- **Testing:** Helping to test the Helm chart in different Kubernetes environments and providing feedback on its usability and functionality.

**Comment by shanginn** [comment]
I will start with providing an example just to get the ball rolling. not very production ready, but works for me.
This is probably will work with default newly created helm chart with name chartname.

```yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "chartname.fullname" . }}-buggregator
  labels:
    {{- include "chartname.labels" . | nindent 4 }}
spec:
  replicas: 1
  selector:
    matchLabels:
      {{- include "chartname.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "chartname.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "chartname.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: "{{ .Release.Name }}"
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "ghcr.io/buggregator/server:{{ .Values.imageBuggregator.tag }}"
          imagePullPolicy: {{ .Values.imageBuggregator.pullPolicy }}
          ports:
            - containerPort: 8000
              name: buggregator-dashboard
            - containerPort: 1025
              name: smtp
            - containerPort: 9912
              name: var-dumper
            - containerPort: 9913
              name: monolog
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}

---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "chartname.fullname" . }}-buggregator
  labels:
    {{- include "chartname.labels" . | nindent 4 }}
spec:
    type: ClusterIP
    ports:
        - port: 8000
          targetPort: 8000
          protocol: TCP
          name: buggregator-dashboard
        - port: 1025
          targetPort: 1025
          protocol: TCP
          name: smtp
        - port: 9912
          targetPort: 9912
          protocol: TCP
          name: var-dumper
        - port: 9913
          targetPort: 9913
          protocol: TCP
          name: monolog
    selector:
        {{- include "chartname.selectorLabels" . | nindent 4 }}
    {{- end }}
    {{- if .Values.imageBuggregator.enabled }}
    {{- $fullName := include "chartname.fullname" . -}}
```

and values.yaml with:
```yaml
imageBuggregator:
  pullPolicy: Always
  tag: "1.10.4"
```

**Comment by Richarddesk** [comment]
Hi! I noticed there hasn't been any recent activity on this issue.
If the work on it is paused, I'm available to take it over and continue. Please let me know if it's okay for me to start working on it. Thanks!

**Comment by butschster** [comment]
@Richarddesk Hey! Let's do it!

**Comment by shanginn** [comment]
updated helm with correct selectors and liveness probes.

```yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "app.fullname" . }}-buggregator
  labels:
    {{ include "app.labels" . | nindent 4 }}
    app.kubernetes.io/component: buggregator
spec:
  replicas: 1
  selector:
    matchLabels:
      {{ include "app.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: buggregator
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{ toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{ include "app.selectorLabels" . | nindent 8 }}
        app.kubernetes.io/component: buggregator
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{ toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "app.serviceAccountName" . }}
      securityContext:
        {{ toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: buggregator
          securityContext:
            {{ toYaml .Values.securityContext | nindent 12 }}
          image: "ghcr.io/buggregator/server:{{ .Values.imageBuggregator.tag }}"
          imagePullPolicy: {{ .Values.imageBuggregator.pullPolicy }}
          ports:
            - containerPort: 8000
              name: dashboard
            - containerPort: 1025
              name: smtp
            - containerPort: 9912
              name: var-dumper
            - containerPort: 9913
              name: monolog
          livenessProbe:
            httpGet:
              path: /
              port: dashboard
            initialDelaySeconds: 15
            periodSeconds: 20
          readinessProbe:
            httpGet:
              path: /
              port: dashboard
            initialDelaySeconds: 5
            periodSeconds: 10
          resources:
            {{ toYaml .Values.resources | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{ toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{ toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{ toYaml . | nindent 8 }}
      {{- end }}

---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "app.fullname" . }}-buggregator
  labels:
    {{ include "app.labels" . | nindent 4 }}
    app.kubernetes.io/component: buggregator
spec:
  type: ClusterIP
  ports:
    - port: 8000
      targetPort: 8000
      protocol: TCP
      name: dashboard
    - port: 1025
      targetPort: 1025
      protocol: TCP
      name: smtp
    - port: 9912
      targetPort: 9912
      protocol: TCP
      name: var-dumper
    - port: 9913
      targetPort: 9913
      protocol: TCP
      name: monolog
  selector:
    {{ include "app.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: buggregator
```
