### ISSUE TITLE
[BUG][1.8.0] Server crashing when using MongoDB

### ISSUE THREAD

**Issue by gander** [buggregator/server#179]
### With MongoDB:

```yaml
services:
    buggregator:
        image: ghcr.io/buggregator/server:latest
        depends_on:
            buggregator-db:
                condition: service_healthy
        ports:
            - 127.0.0.1:8000:8000
        environment:
            PERSISTENCE_DRIVER: 'mongodb'
            MONGODB_CONNECTION: 'mongodb://buggregator-db:27017'
            MONGODB_DATABASE: 'buggregator'

    buggregator-db:
        image: mongo:latest
        healthcheck:
            test: [ "CMD-SHELL", "mongosh --eval 'db.runCommand({ping: 1}).ok' || exit 1" ]
            interval: 3s
            timeout: 3s
            retries: 3
```

```
buggregator-1  | handle_serve_command: Function call error:
buggregator-1  |        serve error from the plugin *centrifuge.Plugin stopping execution, error: static_pool_allocate_workers: WorkerAllocate: EOF
buggregator-1 exited with code 1
```

### Without DB:

```yaml
services:
    buggregator:
        image: ghcr.io/buggregator/server:latest
        ports:
            - 127.0.0.1:8000:8000
```

```
buggregator-1  | 2024-05-20T08:38:41+0000       ERROR   app             Unable to declare consumer pipeline "memory". Reason: Error 'rpc_declare_pipeline: pipeline already exists, name: local, driver: memory' on tcp://127.0.0.1:6001 [] []
buggregator-1  | 
buggregator-1  | 2024-05-20T08:38:41+0000       ERROR   app             Unable to declare consumer pipeline "memory". Reason: Error 'rpc_declare_pipeline: pipeline already exists, name: local, driver: memory' on tcp://127.0.0.1:6001 [] []
buggregator-1  | 
buggregator-1  | 2024-05-20T08:38:41+0000       ERROR   app             Unable to declare consumer pipeline "memory". Reason: Error 'rpc_declare_pipeline: pipeline already exists, name: local, driver: memory' on tcp://127.0.0.1:6001 [] []
buggregator-1  | 
buggregator-1  | 2024-05-20T08:38:41+0000       ERROR   app             Unable to declare consumer pipeline "memory". Reason: Error 'rpc_declare_pipeline: pipeline already exists, name: local, driver: memory' on tcp://127.0.0.1:6001 [] []
buggregator-1  | 
buggregator-1  | [INFO] RoadRunner server started; version: 2023.3.7, buildtime: 2023-11-30T19:15:58+0000
buggregator-1  | [INFO] sdnotify: not notified
```
