### ISSUE TITLE
404 on http://127.0.0.1:8000/sentry/1.js

### ISSUE THREAD

**Issue by soderlind** [buggregator/server#188]
I'm getting a 404 when I try to load `http://127.0.0.1:8000/sentry/1.js`, as in:

```html
<script src="http://127.0.0.1:8000/sentry/1.js"></script>
```

This is my `docker-compose.yml`
```yml
services:
    buggregator:
        image: ghcr.io/buggregator/server:latest
        depends_on:
            buggregator-database:
                condition: service_healthy
        ports:
            - 127.0.0.1:8000:8000
        environment:
            PERSISTENCE_DRIVER: database
            DB_DRIVER: pgsql
            DB_DATABASE: buggregator
            DB_HOST: buggregator-database
            DB_PORT: 5432
            DB_USERNAME: buggregator
            DB_PASSWORD: buggregator
            SENTRY_JS_SDK_URL: https://browser.sentry-cdn.com/7.69.0/bundle.tracing.replay.min.js
            SENTRY_JS_DSN_HOST: http://sentry@127.0.0.1:8000

    buggregator-database:
        image: postgres:latest
        healthcheck:
            test: [ "CMD-SHELL", "pg_isready --username=buggregator --dbname=buggregator" ]
            interval: 3s
            timeout: 3s
            retries: 1
        environment:
            POSTGRES_DB: buggregator
            POSTGRES_USER: buggregator
            POSTGRES_PASSWORD: buggregator
```
