### ISSUE TITLE
XHProf profiler for laravel

### ISSUE THREAD

**Issue by webard** [buggregator/server#23]
Hello,
is it possible to combine the xhrof viewer with laravel?

**Comment by butschster** [comment]
Hello. 

Yes, you can use the [Profiler package]( https://github.com/spiral-packages/profiler) to integrate XHProf profiler with your Laravel application.

To bind the Profiler classes into the Laravel container, you can refer to the example in the [ProfilerBootloader.php](https://github.com/spiral/profiler/blob/3.0/src/ProfilerBootloader.php) file. This example demonstrates how to bootstrap the Profiler and bind it to the Laravel container.
I hope this helps! Let me know if you have any further questions.

**Comment by maantje** [comment]
Created a basic repo to kick off Laravel support. Check it out [here](https://github.com/maantje/xhprof-buggregator-laravel). It's functional, but still a work in progress. Your input is welcome! 🛠️

**Comment by butschster** [comment]
> Created a basic repo to kick off Laravel support. Check it out [here](https://github.com/maantje/xhprof-buggregator-laravel). It's functional, but still a work in progress. Your input is welcome! 🛠️

Hi @maantje 

Thx for the package. I've added it to the project readme!

**Comment by maantje** [comment]
Hey @butschster,

It's great to know that the package found its way into the project readme.

I've just rolled out a new release that automatically registers the middleware but also introduces support for toggling the profiler using a header, similar to the spiral/profiler package.

I noticed that the "Using buggregator with Docker Compose" section in the project readme is incomplete for Laravel. To make it work with Sail, make sure to add it to the sail network. Without this step, the framework won't be able to establish a connection with the server.

```
services:
    # ...

    buggregator:
        image: ghcr.io/buggregator/server:dev
        ports:
            - 8000:8000
            - 1025:1025
            - 9912:9912
            - 9913:9913
     networks:
         - sail

```

Thank you for the effort you put into this; I'm really enjoying using it!
