### ISSUE TITLE
Ray Dump support

### ISSUE THREAD

**Issue by menthol** [buggregator/server#24]
Hello,

I don't see the compatibility with Ray dump anymore, did you remove it? 
Is it planned in a future version?

**Comment by butschster** [comment]
Hi! Yes, it's planned after we bring in order a new frontend. Maybe in 2 weeks.

**Comment by menthol** [comment]
I can help for the frontend part

**Comment by butschster** [comment]
https://myray.app/

**Comment by butschster** [comment]
![image](https://github.com/buggregator/spiral-app/assets/773481/c2a84d40-fc99-4bde-b87f-ea81cc1daa17)

**Comment by butschster** [comment]
Hi @menthol 
I've just finished working on module https://github.com/buggregator/spiral-app/pull/43. I didn't finish only `mailable` type. If you want you can try to finish and maybe polish frontend. There is storybook with all required mocks for ray components

**Comment by Semdevmaster** [comment]
Ray integration in Laravel doesn't work in any recent releases: dev, lastest, rc
I am using docker and compose

docker-compose.yml
```yml
    buggregator:
      image: ghcr.io/buggregator/server:dev
      container_name: buggregator-${APP_HOST}
      ports:
        - 8000:8000
      networks:
        - docker-server
```

.env part
```env
RAY_HOST=buggregator
RAY_PORT=8000
```
The ray() function works in the code, but the buggregator interface is empty, while Symphony var_dumper works fine!
