### ISSUE TITLE
Better tags and labels for Docker container builds

### ISSUE THREAD

**Issue by Sn0wCrack** [buggregator/server#252]
Hi there,

I've noticed that the Dockerhub tags don't include tags for all semver versions such as 1, 1.11, etc. and just tag against latest and the specific version, so making sure we always fetch the latest v1 version currently isn't possible.

You should be able to do this fairly easily with the official Docker Metadata Action: https://github.com/docker/metadata-action

An example of how to do this is as follows:

```yaml
  - name: Extract metadata (tags, labels) for Docker
    id: docker_meta
    uses: docker/metadata-action@v5
    with:
      images: butschster/buggregator
      tags: |
        type=semver,pattern={{version}}
        type=semver,pattern={{major}}.{{minor}}
        type=semver,pattern={{major}}
      
  - name: Build and Push Docker Container
    uses: docker/build-push-action@v6
    with:
      context: ./
      file: ./.docker/Dockerfile
      push: true
      platforms: linux/amd64,linux/arm64
      tags: ${{ steps.docker_meta.outputs.tags }}
      labels: ${{ steps.docker_meta.outputs.labels }}
      cache-from: type=gha
      cache-to: type=gha,mode=max
```

This will also automatically create the OpenContainers Labels and apply them as well: https://github.com/opencontainers/image-spec/blob/main/annotations.md
