### ISSUE TITLE
Cannot start server at all `static_pool_allocate_workers: WorkerAllocate: EOF`

### ISSUE THREAD

**Issue by FluffyDiscord** [buggregator/server#59]
I am not sure what is going on since my first buggregator service in a different docker compose works fine, but this one is failing to start. The exposed ports are different.

```
buggregator  | handle_serve_command: Serve error:
buggregator  |   endure_start:
buggregator  |   endure_serve_internal: Function call error:
buggregator  |   endure_call_serve_fn: got initial serve error from the Vertex tcp.Plugin, stopping execution, error: static_pool_allocate_workers: WorkerAllocate: EOF
```

```yaml
version: "3.8"

networks:
  my-network:
    driver: bridge

services:
  buggregator:
    stop_grace_period: 1s
    stop_signal: SIGKILL
    image: ghcr.io/buggregator/server:latest
    networks:
      - my-network
    ports:
      - "8065:8000"
```
