### ISSUE TITLE
Ray integration in Laravel doesn't work in any recent releases: dev, lastest, rc

### ISSUE THREAD

**Issue by Semdevmaster** [buggregator/server#75]
Ray integration in Laravel doesn't work in any recent releases: dev, lastest, rc
I am using docker and compose

docker-compose.yml
```yml
    buggregator:
      image: ghcr.io/buggregator/server:dev
      container_name: buggregator-${APP_HOST}
      ports:
        - 8000:8000
      networks:
        - docker-server
```

.env part
```env
RAY_HOST=buggregator
RAY_PORT=8000
```
The ray() function works in the code, but the buggregator interface is empty, while Symphony var_dumper works fine!

There is an error in the browser console
![image](https://github.com/buggregator/spiral-app/assets/2706508/483122d5-51f0-4ac0-80bd-d51320d7557a)

_Originally posted by @Semdevmaster in https://github.com/buggregator/server/issues/24#issuecomment-1549146904_
