### ISSUE TITLE
Inspector not working in Laravel app

### ISSUE THREAD

**Issue by binaryfire** [buggregator/server#99]
Hi guys

It seems Inspector isn't working in Laravel. Sending to [inspector.dev](https://inspector.dev) works correctly but not sending to Buggregator. I'm using the latest v1.0.0 Docker image. 

The [docs](https://docs.buggregator.dev/config/inspector.html#laravel) say this should be the config:

```
INSPECTOR_URL=http://inspector@127.0.0.1:8000
INSPECTOR_API_KEY=test
INSPECTOR_INGESTION_KEY=1test
INSPECTOR_ENABLE=true
```

But [this line](https://github.com/buggregator/server/blob/88e29c51ece85dfb2777704b5b2002d576a37d34/app/modules/Inspector/Interfaces/Http/Handler/EventHandler.php#L56) in the Inspector `EventHandler` suggests the uri should end with `inspector`?

I tried the above config and the following two configs with no luck:

```
INSPECTOR_URL=http://127.0.0.1:8000/api/inspector
INSPECTOR_API_KEY=test
INSPECTOR_INGESTION_KEY=1test
INSPECTOR_ENABLE=true
```

```
INSPECTOR_URL=http://127.0.0.1:8000/inspector
INSPECTOR_API_KEY=test
INSPECTOR_INGESTION_KEY=1test
INSPECTOR_ENABLE=true
```

Any ideas?

Thanks again!

**Comment by butschster** [comment]
Hi @binaryfire,

If you are using it inside a Docker container, it might be something like:

```
INSPECTOR_URL: http://inspector@buggregator:8000
INSPECTOR_API_KEY: test
```

Where `buggregator` is the container name.

Alternatively, the issue could be incorrect port mapping. If you map a port inside the container to your host server, like `-p 8080:8000`, then you should use port `8080`.

**Comment by binaryfire** [comment]
Hi @butschster 

Yeah actually I'm using the container name. I used `127.0.0.1` in the examples above to avoid confusion :) I don't think that's the problem because these work perfectly:

```
RAY_HOST=ray@buggregator
RAY_PORT=8000

LOG_CHANNEL=socket
LOG_SOCKET_URL=buggregator:9913

VAR_DUMPER_FORMAT=server
VAR_DUMPER_SERVER=tcp://buggregator:9912
```

But this doesn't:

```
INSPECTOR_URL=http://inspector@buggregator:8000
INSPECTOR_API_KEY=test
INSPECTOR_INGESTION_KEY=1test
INSPECTOR_ENABLE=true
```

or

```
INSPECTOR_URL=http://buggregator:8000/api/inspector
INSPECTOR_API_KEY=test
```

**Comment by butschster** [comment]
Hmmm. I you the same settings in examples,

```yaml
services:
  examples:
    build: "./docker/examples"
    environment:
      APP_ENV: production
      APP_KEY: xxx
      LOG_LEVEL: debug
      BROADCAST_DRIVER: log
      CACHE_DRIVER: array
      QUEUE_CONNECTION: sync
      DB_CONNECTION: sqlite
      DB_DATABASE: ":memory:"
      MAIL_HOST: buggregator
      MAIL_PORT: 1025
      MAIL_ENCRYPTION: null
      MAIL_FROM_ADDRESS: sender@site.com
      MAIL_FROM_NAME: sender
      RAY_HOST: ray@buggregator
      RAY_PORT: 8000
      VAR_DUMPER_SERVER: buggregator:9912
      SENTRY_LARAVEL_DSN: http://sentry@buggregator:8000/123
      LOG_SOCKET_URL: buggregator:9913
      LOG_SLACK_WEBHOOK_URL: http://buggregator:8000/slack
      INSPECTOR_URL: http://inspector@buggregator:8000
      INSPECTOR_API_KEY: test
      PROFILER_ENDPOINT: http://profiler@buggregator:8000
    ports:
      - 9020:8000
  buggregator:
    image: ghcr.io/buggregator/server:latest
```
